### ISSUE TITLE
HTTP POST being fired multiple times even with retry policy == 0

### ISSUE THREAD

**Issue by eatalien** [mcxiaoke/android-volley#46]
When I need to make a POST request, I set retry policy = 0, but when the HTTP request hits the timeout, Volley sends another request (and if the timeout is hit again, it will send another one).

Looks like someone else is seeing the same issue here: http://stackoverflow.com/questions/29034735/volley-makes-duplicate-post-call-at-timeout-mark

I'm experiencing it with 1.0.8, 1.0.10, 1.0.15. I didn't try other releases.

This is a major issue because POSTs are by definition not idempotent and I can't find a workaround using Volley with POSTs.

**Comment by panxw** [comment]
There are some kind of exception would  always retry.

**Comment by mcxiaoke** [comment]
@eatalien try to add this header to your  `"Connection": "close"`

**Comment by mcxiaoke** [comment]
@eatalien maybe fixed in v1.0.16, now default max retry is 0, see this commit: cee2e78731f6c74cac13de5070e2609f61db848c

**Comment by mcxiaoke** [comment]
fixed.

**Comment by RohanBarve** [comment]
I am using v1.0.18 and still experiencing duplicate post requests on slow network despite retry policy is being set to retry count 0.

**Comment by balavishnu** [comment]
I am also experiencing multiple requests on slow network using v1.0.18 despite setting retry count to 0.
